### ISSUE TITLE
Act "create" seems to be broken

### ISSUE THREAD

**Issue by christianfuerst** [open-orchard/OpenSeed#42]
Right now, it's not possible to create a new account.
Server responds with status 200 and no data in body as a result.

My best guess is that `index.py` calls `Account.create_user(from_client["username"],from_client["passphrase"],from_client["email"]))` while there is no such a function in `openseed_account.py`.

**Comment by bflanagin** [comment]
https://open-orchard.github.io/OpenSeed/docs/core/account. Renamed create_user to create_account given we use the keyword "account" more often than username.
