### ISSUE TITLE
Public Messages

### ISSUE THREAD

**Issue by bflanagin** [open-orchard/OpenSeed#65]
# Story
Used to create "public" posts and comments that can be accessed on OpenSeed using non-blockchain system. 

# Task
- [x] Add needed fields to app_pub_data (better this way)
- [x] Add functions to new abilities
- [x] Documentation

**Comment by levineam** [comment]
I was actually thinking of something a bit different. Something more like:

Developer wants to enable their users to share messages publicly (either in post or comment form) without posting to a blockchain. 

This would enable them to offer to their users the ability to: 
1. post/comment publicly without a blockchain account (guest posts/comments)
2. post/comment publicly while retaining the option to delete their post (mutable posts/comments)
3. post/comment publicly without consuming blockchain resources (post/comment without using up RCs)

**Comment by bflanagin** [comment]
> I was actually thinking of something a bit different. Something more like:
> 
> Developer wants to enable their users to share messages publicly (either in post or comment form) without posting to a blockchain.

At the time of writing I wasn't considering full posts. It should be included for sure. 

> This would enable them to offer to their users the ability to:
> 
> 1. post/comment publicly without a blockchain account (guest posts/comments)
As long as someone has an account I'm good with that. I still hold firm to the "not everyone needs a blockchain account mentality."
> 2. post/comment publicly while retaining the option to delete their post (mutable posts/comments)
Yep.
> 3. post/comment publicly without consuming blockchain resources (post/comment without using up RCs)
